### ISSUE TITLE
AoC 2020

### ISSUE THREAD

**Issue by subesokun** [docToolchain/aoc-2019#326]
Will there be a repo for AoC 2020 :)?

**Comment by rdmueller** [comment]
great that you ask! Let's create one...

**Comment by subesokun** [comment]
Sorry for the extra work 😊

**Comment by rdmueller** [comment]
Here it is! 
Currently, it is just a copy of the 2019 website without the 2019 solutions.
Feel free to modify the design by ending PRs :-)

https://github.com/docToolchain/aoc-2020
https://aoc-2020.netlify.app/

**Comment by rdmueller** [comment]
PS: if you find bug, please open an issue.

**Comment by subesokun** [comment]
Awesome, thanks!
